// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9sqq2L33zC798HeqEEpM6wSsDkdL1Skc',
    appId: '1:213785583488:web:d1777da9b244b280422b65',
    messagingSenderId: '213785583488',
    projectId: 'app-financas-54749',
    authDomain: 'app-financas-54749.firebaseapp.com',
    storageBucket: 'app-financas-54749.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlTbW17ClnkwbahlIJaQFlUwFx88StuCg',
    appId: '1:213785583488:android:3d478be977422585422b65',
    messagingSenderId: '213785583488',
    projectId: 'app-financas-54749',
    storageBucket: 'app-financas-54749.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7H9X1lprgFTGa6qHLSAY03JDsP4dQoN8',
    appId: '1:213785583488:ios:0b2f019d2176f89c422b65',
    messagingSenderId: '213785583488',
    projectId: 'app-financas-54749',
    storageBucket: 'app-financas-54749.firebasestorage.app',
    iosBundleId: 'com.example.appFinancas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7H9X1lprgFTGa6qHLSAY03JDsP4dQoN8',
    appId: '1:213785583488:ios:0b2f019d2176f89c422b65',
    messagingSenderId: '213785583488',
    projectId: 'app-financas-54749',
    storageBucket: 'app-financas-54749.firebasestorage.app',
    iosBundleId: 'com.example.appFinancas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9sqq2L33zC798HeqEEpM6wSsDkdL1Skc',
    appId: '1:213785583488:web:01fee8035544421c422b65',
    messagingSenderId: '213785583488',
    projectId: 'app-financas-54749',
    authDomain: 'app-financas-54749.firebaseapp.com',
    storageBucket: 'app-financas-54749.firebasestorage.app',
  );
}
